apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: default
  labels:
    app: nginx1
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx1
