apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/franktylerva/argocd-application-sets.git
      revision: HEAD
      directories:
      - path: overlays/cluster1/*
  template:
    metadata:
      name: '{{path[2]}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/franktylerva/argocd-application-sets.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default